---
Resources:
  SimpleEC2Instance:
    Type: "AWS::EC2::Instance"
    Properties:
      InstanceType: t3.micro
      ImageId: ami-0ff8a91507f77f867 # AMI ID for your region
      Tags:
        - Key: Name
          Value: MySimpleInstance
